# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6dbce7f716e6db016e5df599939d21c2f5b35b9252ce1630db2100309bfce3341e5c5f71d94c7e4bc486f10c828bb1f92c59908ebe8b4854c6a9e97ecb4b1d56

test:
  secret_key_base: 3049887f56e0f6974dbc7487538398b747cf7a09a0cc5a35113fef2beea81beb0cf74a40aee6dad7e3a371eb4d9f88bce842bd765bc824a67c0e5174ab44a72e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
